---
title: "This is how we did it"
author: "James Currer"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
library(fixest)
library(plotly)
## read in data only if it doesn't already exist in the environment
if (!exists("crime_w_population_w_pcc_data")) {
  source("data_prep.R")
}

## Conservative treatment ####
### table of only PCCs that are Labour in 2012 ####
### this include those that are always abour and those that change.Excluding 2024 election they all happen to move to Conservative
labour_pccs <- pcc_change_table %>% 
  filter(X2012 == "Labour")

### prepare data for regression ####
crime_data_w_treatment_dummy_conservative <- crime_w_population_w_pcc_data %>% 
  ## add in change date, and change type
  left_join(x = labour_pccs %>% 
              select(PFA23NM,
                     when_change,
                     ChangeType),
            y = .,
            by = join_by(PFA23NM)) %>% 
  ## create treatment dummy based on whether it changes party
  mutate(treat = if_else(ChangeType == "One change",
                         1,
                         0)) %>% 
  ## create post dummy based on election when changed]
  mutate(post = if_else((date > when_change),
                           1,
                           0),
         post = if_else(is.na(post),
                        0,
                        post)) %>% 
  ## create a treat x post dummy given heterogeneous timing
  mutate(treatd = treat*post)

### plot it ####
cdaa <- crime_data_w_treatment_dummy_conservative %>%
  filter(!PFA23NM == "London, City of") %>% 
  distinct(FinancialYear,
           FinancialQuarter,
           PFA23NM,
           OffenceGroup,
           .keep_all = T) %>% 
  filter(OffenceGroup == "Criminal damage and arson") %>% 
  ggplot(aes(x=factor(period),y=offence_group_per_100k,colour=factor(treatd))) + 
  geom_point(alpha=0.05) + 
  geom_smooth(aes(x=factor(period),y=offence_group_per_100k,group=factor(treatd)),formula = y~x, method="lm") + 
  theme(panel.grid.minor = element_blank()) +
  theme_bw() +
  labs(title = "Criminal Damage and Arson DiD", x = "Period", y = "Crimes per 100k poulation", color = "1 = Conversative")
```

## Difference in Difference plot for Criminal Damage and Arson

```{r, echo=FALSE, fig.dim = c(12, 6)}
plot(cdaa)
```

